const express = require("express");
const { login, register } = require("./controller/auth-controller");
const router = express.Router();
const passport = require("passport");
const jwtAuth = require("./middlewares/jwt-auth");
const userController = require("./controller/user-controller");
const items = require('./controller/items-controller');
router.post("/register", register).post("/login", login);
router.get("/me", jwtAuth, userController.me);
router.post('/items', jwtAuth,items.createItems);
router.get('/getitemslist',items.getItems);
module.exports = router;
